export enum ConversationState {
  SELECTING_COMPANY = 'selecting_company',
  SELECTING_CATEGORY = 'selecting_category',
  BROWSING_PRODUCTS = 'browsing_products',
  VIEWING_PRODUCT_DETAIL = 'viewing_product_detail',
  SELECTING_PRESENTATION = 'selecting_presentation',
  CONFIRMING_CLIENT_DATA = 'CONFIRMING_CLIENT_DATA',
  COLLECTING_CLIENT_NAME = 'COLLECTING_CLIENT_NAME',
  COLLECTING_CLIENT_ADDRESS = 'COLLECTING_CLIENT_ADDRESS',
  COLLECTING_CLIENT_PHONE = 'COLLECTING_CLIENT_PHONE',
  COLLECTING_CLIENT_GEO = 'COLLECTING_CLIENT_GEO',
}
